#%RAML 1.0 Library
usage: |
  This library defines set of scalar types which are expected to be used in annotations or in RAML dialect
  type declarations. It is expected that RAML processing tools knows and respect them when perform library expansion.
uses:
  n: namespaces.raml
  semanticValidation: semanticValidation.raml
(n.namespace): http//raml.org/vocubalaries/dialectTypes.raml
types:
  RAMLReferenceExpression:
    (semanticValidation.hasSemanticalConstraints):
    type: string
    description: |
      This type allows to describe a reference to the property of RAML type. For example
      `Person.name` is a reference to the property name of the type person,
      It is also allowed to chain property accesses like  in following example `Repository.owner.login`
      type name may be prefixed with library namespace.
    examples:
      Simple: Person.name
      Chaining: Repository.owner.login
      Qualified: github.Repository.owner.login
  RAMLTypeName:
    (semanticValidation.hasSemanticalConstraints):
    description: name of the RAML type, if the type comes from library name should be prefixed with library namespace.
    type: string
    examples:
      SimpleName: Person
      QualifiedName: teams.Person
  RAMLTypeExpression:
    (semanticValidation.hasSemanticalConstraints):
    description: valid type expression in terms of RAML types.
    type: string
    examples:
      simple: string
      array: Person[]
      unionType: teams.Person| Man
  relativeUrl:
     type: string
     (semanticValidation.hasSemanticalConstraints):
     description: valid relative uri
  absoluteUrl:
     (semanticValidation.hasSemanticalConstraints):
     description: valid absolute url
  responseCode:
     (semanticValidation.hasSemanticalConstraints):
     description: valid response code
  mediaType:
     (semanticValidation.hasSemanticalConstraints):
     description: valid media type name
