#%RAML 1.0 Library
annotationTypes:
  namespace:
    description: |
      this annotation types allows you to associate unique identifier with a document,
      it is expected that namespace is a Uniform Resource Identifier (URI).
    type: string
